##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/thesadso/theexactopposite.uk/test
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp -R API $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    /bin/cp index-card-h.html $DEPLOYPATH